### ISSUE TITLE
Cannot get package meta when requirement file uses git+https

### ISSUE THREAD

**Issue by 0ssigeno** [pilosus/pip-license-checker#107]
To reproduce:

1. Create a requirements.txt
```
git+https://github.com/jazzband/django-silk.git 
```

2. Pass in to the checker and get an error
```
lein run --requirements requirements.txt
git+https://github.com/jazzband/django-silk.git                    Error                                                   Error      
```

**Comment by pilosus** [comment]
Hey, thanks for raising this.

Unfortunately, the checker doesn't support license name fetching for packages outside of PyPI package index, as the checker relies heavily on [PyPI JSON API](https://warehouse.pypa.io/api-reference/json.html).

In your case you need some sort of third-party tool to fetch license name from packages local meta first, and the pass it to the license checker.

This is how it can be done with [pip-licenses](https://github.com/raimon49/pip-licenses):

```
# 1. Install your packages you want to check licenses for, in venv, docker whatever
$ pip install -r requirements.txt

# 2. Install pip-licenses tool
$ pip install -U pip-licenses

# 3. Dump packages/licenses as a CSV file:
$ pip-licenses --with-systems --format=csv

# 4. Pass in to the checker
$ lein run --external ~/pip-licenses.csv --external-format=csv --external-options '{:package-column-index 0 :license-column-index 2}'
```

Hope that helps.

Cheers

**Comment by 0ssigeno** [comment]
Thank you for the detailed answer!
I hoped that this could have been supported in the action itself, so that an user could just import this action in its own CI and be done, but I can see the technical issues that this would involve.

Closing the issue, since there is a solution for this problem
